### ISSUE TITLE
Error with pre-commit

### ISSUE THREAD

**Issue by nlamirault** [jtyr/kubeconform-helm#14]
I try this configuration:

```yaml
- repo: https://github.com/jtyr/kubeconform-helm
  rev: v0.1.10
  hooks:
    - id: kubeconform-helm
      args:
        - --kubernetes-version=1.24.0
        - --verbose
        - --summary
```

and for a commit, i've got this error:

```
✖ git commit . -s -m"Fix: missing default values for Freebox Exporter chart"
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check for added large files..............................................Passed
Insert license in comments...............................................Passed
Chart Test: Lint.....................................(no files to check)Skipped
Helm Docs................................................................Passed
Kubeconform Helm.........................................................Failed
- hook id: kubeconform-helm
- exit code: 1

Traceback (most recent call last):
  File "/home/nicolas/.cache/pre-commit/repoe2x4c66s/scripts/pre-commit.py", line 129, in <module>
    main()
  File "/home/nicolas/.cache/pre-commit/repoe2x4c66s/scripts/pre-commit.py", line 40, in main
    log = pw.get_logger(
TypeError: get_logger() missing 1 required positional argument: 'stdout'

black................................................(no files to check)Skipped
```

Any idea ?
