### ISSUE TITLE
--charts-path parameter ignored

### ISSUE THREAD

**Issue by mteodori** [jtyr/kubeconform-helm#19]
it seems that the option to change the path where the helm chart to validate lives is ignored due to the value being hardcoded in the files property of the hook definition:

https://github.com/jtyr/kubeconform-helm/blob/main/.pre-commit-hooks.yaml#L6

in order to work in another dir like `src/helm` I have to supply a files property in my pre-commit configuration like this

```
      - id: kubeconform-helm
        verbose: true
        files: ^(helper-|)src/helm/[^/]+/(\.kubeconform|\.helmignore|templates/NOTES.txt|.*\.(ya?ml|json|tpl))$
        args:
          - --charts-path=src/helm
```
